import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Navbar from "@/components/Navbar";
import CursorEvent from "@/components/CursorEvent";
import { Playfair_Display,Source_Sans_3 as Source_Sans_Pro } from "next/font/google";
import "./globals.css";


const playfairDisplay = Playfair_Display({
  variable: "--font-heading",
  display: "swap",
  subsets: ["latin"],
});

const sourceSansPro = Source_Sans_Pro({
  variable: "--font-body",
  display: "swap",
  subsets: ["latin"],
  weight:['400','600','700']
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My-site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      
      <body
        className={"antialiased"}
      >
        <Navbar />
        <CursorEvent />
        {children}
      </body>
    </html>
  );
}
